[package]
name = "squ1d-renderer"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[[bin]]
name = "renderer"
path = "src/main.rs"

[lib]
name = "squ1d_renderer"
path = "src/lib.rs"
